name: Release

on:
  push:
    branches:
      - 'next'
      - 'latest'

jobs:
  release:
    name: Build release candidate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          # The Node.js version to configure
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:all
      - name: Test
        run: npm test
      - name: Build
        run: npm run build

  publish-npm:
    name: Publish to npm
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # The Node.js version to configure
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish to npm (${GITHUB_REF##*/})
        run: npm publish --tag ${GITHUB_REF##*/}
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
